-- V1__Create_initial_schema.sql

-- Tabela de Dispositivos
CREATE TABLE dispositivos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    localizacao VARCHAR2(255 CHAR) NOT NULL,
    tipo VARCHAR2(50 CHAR) NOT NULL,
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP,
    ativo NUMBER(1) DEFAULT 1 NOT NULL CHECK (ativo IN (0,1))
);

-- Tabela de Leituras de Consumo
CREATE TABLE leituras_consumo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id NUMBER NOT NULL,
    valor NUMBER(19,4) NOT NULL,
    unidade_medida VARCHAR2(20 CHAR) NOT NULL,
    data_hora_leitura TIMESTAMP NOT NULL,
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_leitura_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivos(id)
);

-- Tabela de Tipos de Alerta (Enum)
-- Como Oracle não suporta ENUM diretamente como MySQL ou PostgreSQL, usaremos uma tabela de lookup ou constraints.
-- Para simplificar, vamos usar uma constraint na tabela configuracoes_alerta e ocorrencias_alerta.

-- Tabela de Configurações de Alerta
CREATE TABLE configuracoes_alerta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dispositivo_id NUMBER NOT NULL UNIQUE,
    limite_consumo NUMBER(19,4) NOT NULL,
    unidade_limite VARCHAR2(20 CHAR) NOT NULL,
    tipo_alerta VARCHAR2(50 CHAR) NOT NULL CHECK (tipo_alerta IN ('ACIMA_DO_LIMITE', 'ABAIXO_DO_LIMITE', 'DESCONEXAO_DISPOSITIVO', 'FALHA_LEITURA', 'MANUTENCAO_PREVISTA')),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP,
    ativo NUMBER(1) DEFAULT 1 NOT NULL CHECK (ativo IN (0,1)),
    CONSTRAINT fk_config_alerta_dispositivo FOREIGN KEY (dispositivo_id) REFERENCES dispositivos(id)
);

-- Tabela de Ocorrências de Alerta
CREATE TABLE ocorrencias_alerta (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    configuracao_alerta_id NUMBER NOT NULL,
    tipo_alerta_ocorrencia VARCHAR2(50 CHAR) NOT NULL CHECK (tipo_alerta_ocorrencia IN ('ACIMA_DO_LIMITE', 'ABAIXO_DO_LIMITE', 'DESCONEXAO_DISPOSITIVO', 'FALHA_LEITURA', 'MANUTENCAO_PREVISTA')),
    descricao VARCHAR2(1000 CHAR) NOT NULL,
    data_hora_ocorrencia TIMESTAMP NOT NULL,
    valor_registrado NUMBER(19,4),
    resolvido NUMBER(1) DEFAULT 0 NOT NULL CHECK (resolvido IN (0,1)),
    data_resolucao TIMESTAMP,
    observacoes_resolucao VARCHAR2(1000 CHAR),
    CONSTRAINT fk_ocorrencia_config_alerta FOREIGN KEY (configuracao_alerta_id) REFERENCES configuracoes_alerta(id)
);

-- Índices para melhor performance em consultas frequentes
CREATE INDEX idx_leituras_dispositivo_data ON leituras_consumo (dispositivo_id, data_hora_leitura);
CREATE INDEX idx_ocorrencias_config_data ON ocorrencias_alerta (configuracao_alerta_id, data_hora_ocorrencia);

